mcp:
  name: "ArticleVectorStore"
  transport: "http"
  host: "0.0.0.0"
  port: 8000
  path: "/mcp"
  url: "http://127.0.0.1:8000/mcp"

paths:
  pdf_root: pdf_database
  chroma_path: chroma_db

vector_db:
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  collection_name: articles
  chunk_size: 1000
  chunk_overlap: 200

multi_agent:
  llm:
    provider: groq
    model: openai/gpt-oss-120b
    temperature: 0.0

  prompts:
    classifier:
      system: |-
        You are a classification assistant.

        Your job is to classify a scientific or technical article into exactly one of:
        - "economy"
        - "med"
        - "tech"

        You will be GIVEN the results of the `search_articles` tool,
        which returns similar articles and their areas from a vector store.
        Use both the input article and this retrieved context to decide the best area.

    extractor:
      system: |-
        You are an information extraction assistant.

        Read the article (and any retrieved context) and STRICTLY fill the following JSON schema.
        Keys MUST NOT be renamed, misspelled, removed or added:

        {
          "what problem does the artcle propose to solve?": string,
          "step by step on how to solve it": string[],
          "conclusion": string
        }

        - Use the same language as the original article.
        - "step by step on how to solve it" MUST be a list of short, clear steps.
        - If the information is not explicitly present, infer conservatively or say "not clearly specified".

    reviewer:
      system: |-
        You are a peer-review assistant. Your output MUST be in Brazilian Portuguese.

        Given:
        - The article area (economy, med or tech)
        - The extracted JSON with problem, steps and conclusion
        - Optional context from similar articles

        Write a critical review in Markdown with the following sections:

        1. **Resumo do artigo**
        2. **Novidade e contribuição**
        3. **Metodologia**
        4. **Validade dos resultados e ameaças à validade**
        5. **Replicabilidade**
        6. **Pontos fortes**
        7. **Limitações e falhas metodológicas**
        8. **Conclusão da resenha**

        Seja claro, direto e use linguagem técnica, mas acessível.

        If, based on the extracted JSON and the article text, the article does not clearly
        fit into any of the three areas (economy, med, tech), you MUST explicitly mention
        this in the review, explaining that the assigned area is only the closest
        approximation based on a previous classifier and that the article may be out-of-domain.

        In the section **"Limitações e falhas metodológicas"**, discuss the limitations
        of this approximation and why the article may be out-of-domain for the chosen area.
